#!/usr/bin/env node
const execSync = require('child_process').execSync
execSync('cd ./docs/.vuepress/dist')
execSync('git init')
execSync('git add -A')
execSync('git commit -m "deploy"')
execSync('git push -f git@github.com:Elias-cug/elias-cug.github.io.git master')
